idf_component_register(
    SRCS
        "BipedStep.cpp"
        "ContactKinematics.cpp"
        "ContactStep.cpp"
        "FootTrajectory.cpp"
        "GaitPhase.cpp"
        "LegKinematics.cpp"
        "MotionClip.cpp"
        "MotionLibrary.cpp"
        "PoseInterpolator.cpp"
        "PoseLibrary.cpp"
        "RobotKinematics.cpp"
    INCLUDE_DIRS "include"
)
